// 여섯 식구 첫 여행 · 오프라인 저장
const CACHE='tw-v6';
const PRE=["./", "index.html", "manifest.webmanifest", "icon-192.png", "apple-touch-icon.png", "img/101.jpg", "img/chiikawa.jpg", "img/cks.jpg", "img/day1.jpg", "img/day2.jpg", "img/day3.jpg", "img/day4.jpg", "img/donki.jpg", "img/f_amei.jpg", "img/f_beef.jpg", "img/f_bento.jpg", "img/f_boar.jpg", "img/f_boba.jpg", "img/f_charsiu.jpg", "img/f_chicken.jpg", "img/f_congee.jpg", "img/f_court.jpg", "img/f_duck.jpg", "img/f_fruit.jpg", "img/f_gopchang.jpg", "img/f_hotpot.jpg", "img/f_kiki.jpg", "img/f_lurou.jpg", "img/f_mango.jpg", "img/f_peanut.jpg", "img/f_pepper.jpg", "img/f_ribs.jpg", "img/f_sausage.jpg", "img/f_shandi.jpg", "img/f_wing.jpg", "img/flight.jpg", "img/hero.jpg", "img/hotel.jpg", "img/houtong.jpg", "img/jinguashi.jpg", "img/jiufen.jpg", "img/longshan.jpg", "img/ovbase.jpg", "img/ovdetail.png", "img/overview.jpg", "img/r_jiufen.jpg", "img/r_shifen.jpg", "img/r_wulai.jpg", "img/r_yehliu.jpg", "img/raohe.jpg", "img/redhouse.jpg", "img/shifen.jpg", "img/trolley.jpg", "img/wannian.jpg", "img/wulai.jpg", "img/wulaifall.jpg", "img/wulaist.jpg", "img/wulaivil.jpg", "img/ximen.jpg", "img/ximenug.jpg", "img/yehliu.jpg", "img/yongkang.jpg"];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>Promise.all(PRE.map(u=>c.add(u).catch(()=>{})))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);
  const same=u.origin===self.location.origin;const font=/fonts\.(googleapis|gstatic)\.com$/.test(u.hostname);if(!same&&!font)return;
  if(r.mode==='navigate'||(same&&/\/(index\.html)?$/.test(u.pathname))){
    e.respondWith(fetch(r).then(res=>{const cp=res.clone();caches.open(CACHE).then(c=>c.put('index.html',cp));return res}).catch(()=>caches.match('index.html').then(m=>m||caches.match('./'))));return}
  e.respondWith(caches.match(r,{ignoreSearch:true}).then(m=>{const net=fetch(r).then(res=>{if(res&&(res.ok||res.type==='opaque')){const cp=res.clone();caches.open(CACHE).then(c=>c.put(r,cp))}return res}).catch(()=>m);return m||net}))});
